_prefs: 
  baselayer: ''
  mapid: ''
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -122.7887
  - 47.3983
  - 8
description: A map for running, biking, and hiking
format: "png8:m=h:c=128"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Run, Bike, and Hike
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6"
styles: 
  - vars.mss
  - bg.mss
  - labels.mss
  - roads.mss
  - pois.mss
template: ''
