_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 7.5586
  - 52.7762
  - 5
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 18
minzoom: 0
name: Monomap
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - road.mss
  - data.mss
  - labels.mss
template: ''
