_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -65.5252
  - 48.8304
  - 9
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 15
minzoom: 0
name: ''
source: "mapbox:///mapbox.mapbox-streets-v5,jonathanlurie.3ginqncu"
styles: 
  - style.mss
template: ''
